spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create  #엔티티 정보를 지우고 다시 생성
    properties:
      hibernate:
        #show_sql: true  #System.out에 출력
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug  #하이버네이트가 생성하는 SQL 콘솔로깅
    org.hibernate.type: trace #쿼리 파라미터 로그 남기기